[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#F26D24"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F5"
textColor = "#1F2937"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
